spring:
  application:
    name: forklog_backend

  profiles:
    include: secret
    # dev, prod
    active: dev

  jpa:
    # 지연로딩 설정
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # feign configuration
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 5000
        ok-http:
          read-timeout: 5000

  # file upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      # react project path mapping
      add-mappings: true

server:
  port: 8080

# security logging
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG

    # feign log
    com:
      acorn:
        api:
          openfeign:
            KakaoRestOpenFeign: DEBUG

# upload directory
file:
  upload-dir: ./uploads